steps:
  # Docker 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/newsscrap:$COMMIT_SHA', '.']

  # Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/newsscrap:$COMMIT_SHA']

  # Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'newsscrap'
      - '--image'
      - 'gcr.io/$PROJECT_ID/newsscrap:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/newsscrap:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  serviceAccount: '753507636298-compute@developer.gserviceaccount.com' 